server:
  port: 7890
spring:
  application:
    name: consumer_1
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
#          auto-create-topics: true
      bindings:
#input是接收，注意这里不能再像前面一样写output了
        input:
          destination: stream-demo
          group: group
#          consumer:
#            partitioned: true
#      instance-count: 2
#      instance-index: 1